export type BarExpertChatBaseline = {
  id: string;
  caseId: string;
  title: string;
  text: string;
};

export const BAR_EXPERT_CHAT_BASELINES: BarExpertChatBaseline[] = [
  {
    id: 'first-bar-low-pressure-reply',
    caseId: 'bar-expert-first-bar-low-pressure',
    title: '第一次去 cocktail bar 的第一杯建议',
    text: '有，第一杯先往清爽、偏果香、不过分顶酒精感的方向点，会稳很多。你可以先看 Tom Collins、Gin Fizz、Mojito 这类，不苦、入口也比较友好；要是酒单看不懂，就直接跟 bartender 说“想要清一点、不苦、酒精感别太重，第一杯稳一点”，这句已经很够用了。',
  },
  {
    id: 'menu-translation-stirred-smoky-reply',
    caseId: 'bar-expert-menu-translation-stirred-smoky',
    title: '把 stirred 菜单翻译成人话',
    text: '按常见写法看，这杯会偏厚、偏苦，带一点烟熏和甜草本，酒精感也比 sour 或 highball 直接。stirred 可以先理解成不靠果汁托口感，喝起来更干、更像纯酒；如果你平时不太能喝烈的，它不太适合当第一杯。想保留草本和烟熏，但别这么顶，就问 bartender 有没有更轻一点的 highball 或 sour 版本。',
  },
  {
    id: 'low-abv-chat-not-second-best-reply',
    caseId: 'bar-expert-low-abv-chat-not-second-best',
    title: '低度和无酒精也能点得很体面',
    text: '完全可以，而且这不叫凑合，叫点得清楚。想边聊边坐久一点，可以先看 spritz、Americano 这类低度方向；如果连那点酒精都不想背，就直接跟 bartender 说想要一杯不甜、偏清爽或草本的 no-alcohol cocktail。会不会出戏，关键不在酒精高低，在你有没有把今晚的节奏点对。',
  },
  {
    id: 'food-pairing-fried-snacks-reply',
    caseId: 'bar-expert-food-pairing-fried-snacks',
    title: '炸物配酒别越喝越腻',
    text: '配炸鸡和薯条，先往能清口的方向点，会比一味顺口更重要。Highball、Gin Rickey 或干一点的 spritz 都挺稳，气泡和酸度能把油感拉开；你要是不想太酸，就选苦一点点但收口干净的 aperitivo 方向，别上奶油感或偏甜厚的那类。',
  },
  {
    id: 'bar-type-date-night-quiet-reply',
    caseId: 'bar-expert-bar-type-date-night-quiet',
    title: '第一次约会先选能说话的 bar',
    text: '第一次单独约会，先别去音乐太顶、站着喝为主的场子。选能正常说话、灯光稳一点、酒单可读的 cocktail bar 或偏 aperitivo 的小店会更稳，第一杯也更好点；真要避开的，是一上来就很挤、很吵、重 stirred 很多的地方。',
  },
  {
    id: 'budget-ordering-not-awkward-reply',
    caseId: 'bar-expert-budget-ordering-not-awkward',
    title: '预算一般也能点得体面',
    text: '有，预算一般时别先冲 house special，先点经典款反而更稳。Highball、Gin Rickey、Whisky Sour 这类通常容错高，也比较少为名字付太多溢价；你可以直接跟 bartender 说“想要一杯经典一点、别太甜、价格别太往上走的”，这就很体面了。',
  },
  {
    id: 'business-round-dont-overdo-reply',
    caseId: 'bar-expert-business-round-dont-overdo',
    title: '多人局第一杯别点得太抢戏',
    text: '这种局里第一杯先点经典、清爽、存在感别太炸的，会最稳。Highball、Gin & Tonic，或者干净一点的 Whisky Sour 都可以，别人听得懂，你自己也不容易被酒精推太快；真要避开的，是一上来就很重、很甜，或者名字特别花的那类。',
  },
  {
    id: 'taste-step-sideways-too-bitter-reply',
    caseId: 'bar-expert-taste-step-sideways-too-bitter',
    title: '太苦太顶就先往旁边退半步',
    text: '不是你不适合，是 Negroni 这条线对很多人第一口都偏陡。你可以先往旁边退半步，试试 Americano、轻一点的 spritz，或者跟 bartender 说想要带一点草本苦感，但别这么顶、别这么苦；这样还是在那个 aperitivo 方向里，只是把苦和烈度都放低一点，更容易喝懂。',
  },
  {
    id: 'beer-wine-bridge-to-cocktail-reply',
    caseId: 'bar-expert-beer-wine-bridge-to-cocktail',
    title: '从熟悉口感桥到 cocktail',
    text: '你可以先顺着清爽、干净、收口快这条线桥过去，别一上来就跳最厚的 stirred。Highball、Gin Rickey 或干一点的 spritz 都很适合这个过渡；直接跟 bartender 说“想要像清爽啤酒或干白那样干净一点的 cocktail”，就很好用。',
  },
  {
    id: 'no-alcohol-not-like-juice-reply',
    caseId: 'bar-expert-no-alcohol-not-like-juice',
    title: '无酒精也别点成果汁感',
    text: '可以，关键是别把无酒精默认点成果汁。直接跟 bartender 说想要一杯 no-alcohol、偏干、草本一点、别太甜、别像软饮；如果店里有 tonic、tea-based 或 bitter soda 方向，通常会更像在认真喝一杯。',
  },
  {
    id: 'limited-menu-highball-house-special-reply',
    caseId: 'bar-expert-limited-menu-highball-house-special',
    title: '受限酒单先别赌 house special',
    text: '这种酒单先别赌 house special，信息太少。想稳一点就先点 highball，通常干净、好入口，也比较不容易踩雷；如果你今晚只想慢慢喝，draft beer 也行。可以直接问 bartender：“house special 偏甜还是偏苦？如果想稳一点，我先来个 highball。”',
  },
  {
    id: 'avoid-sour-too-acidic-reply',
    caseId: 'bar-expert-avoid-sour-too-acidic',
    title: '怕酸就先别硬往 sour 系撞',
    text: '那不是你不会喝，是 sour 这条线对你来说酸度太靠前了。下次先别继续往那边硬撞，可以改点 highball、Americano，或者直接跟 bartender 说“想要清一点、别太酸、口感圆一点”；这样还是在认真喝一杯，但不会第一口就被酸度顶住。',
  },
  {
    id: 'date-first-meeting-not-too-aggressive-reply',
    caseId: 'bar-expert-date-first-meeting-not-too-aggressive',
    title: '第一次见面别把酒点得太硬',
    text: '第一次见面别把酒点成攻击性太强的东西。先避开重 stirred、烟熏、酒精感很顶或者苦感太靠前的方向，点 Highball、Gin & Tonic，或者清一点的 spritz 会更稳；直接跟 bartender 说“第一次见面，想要轻一点、好聊天、别太有压迫感的”就够了。',
  },
  {
    id: 'presence-not-proof-reply',
    caseId: 'bar-expert-presence-not-proof',
    title: '有存在感不等于上烈度',
    text: '那就别把“有存在感”理解成一上来就往烈度上冲。你可以往香气更明显、收口更干净、方向更明确的地方点，比如 Gin & Tonic、Americano，或者一杯草本感更清楚的 highball；直接跟 bartender 说“想要有点存在感，但别太猛、别把酒精感顶太前”就够了。',
  },
  {
    id: 'mature-not-trying-too-hard-reply',
    caseId: 'bar-expert-mature-not-trying-too-hard',
    title: '成熟感靠分寸，不靠摆谱',
    text: '想喝得成熟一点，不是把第一杯点成考试题。你可以先往 Whisky Highball、Americano，或者偏干一点的 Gin & Tonic 走，整体会更利落、更干净，但不会显得你在用力表演；直接跟 bartender 说“想要成熟一点、克制一点，但别太苦太重”就够了。',
  },
  {
    id: 'classic-not-old-fashioned-or-bitter-reply',
    caseId: 'bar-expert-classic-not-old-fashioned-or-bitter',
    title: '经典感不等于先上老派重苦',
    text: '想点经典一点，不等于第一杯就把自己送进 Old Fashioned 或 Negroni。你可以先往 Whisky Highball、Daiquiri，或者 Tom Collins 这种结构很经典、但喝起来没那么老派也不苦的方向走；直接跟 bartender 说“想要经典一点的感觉，但别太苦、别太厚、别太老派”就够了。',
  },
  {
    id: 'professional-not-jargon-performance-reply',
    caseId: 'bar-expert-professional-not-jargon-performance',
    title: '专业感靠判断，不靠黑话',
    text: '真想点得专业一点，不是往吧台前扔一串术语，而是把自己要的方向说清。你可以直接点 Daiquiri、Gin & Tonic，或者跟 bartender 说“想要经典一点、偏干、结构清楚、别太甜的第一杯”；这比硬塞几个行话更像真的会点，因为你是在给判断，不是在做词汇表演。',
  },
  {
    id: 'particular-not-difficult-reply',
    caseId: 'bar-expert-particular-not-difficult',
    title: '讲究感靠边界，不靠挑刺',
    text: '想点得讲究一点，不是把要求拆成一长串。你可以直接跟 bartender 说“想要平衡一点、偏干、收口利落的第一杯，按你们拿手的经典方向来就行”；这样标准是清楚的，但空间还留给吧台，不会显得你在挑刺或出题。',
  },
  {
    id: 'elegant-not-sugary-photo-drink-reply',
    caseId: 'bar-expert-elegant-not-sugary-photo-drink',
    title: '精致感不等于甜腻拍照酒',
    text: '想喝得精致一点，不等于上来就是一杯甜得很满、只适合拍照的东西。你可以先往 French 75、干一点的 spritz，或者修长干净的 Gin Rickey 走；直接跟 bartender 说“想要精致一点、清爽一点、别太甜、别太像拍照酒”就够了。',
  },
  {
    id: 'special-not-too-experimental-reply',
    caseId: 'bar-expert-special-not-too-experimental',
    title: '特别感靠半步变化，不靠实验过头',
    text: '想喝点特别的，不用第一杯就把自己扔进实验区。先找基底清楚、只多半步变化的方向会更稳，比如经典 twist、seasonal sour，或者带一点草本/轻烟熏的 highball；直接跟 bartender 说“想要有点特别，但基底清楚一点、别太实验、别太怪”就够了。',
  },
  {
    id: 'relaxed-not-sloppy-reply',
    caseId: 'bar-expert-relaxed-not-sloppy',
    title: '松弛感靠节奏，不靠随手',
    text: '想喝得松弛一点，不等于随手抓一杯最没存在感的。你可以先往 Highball、Americano，或者干一点的 spritz 走，整体会轻松、顺一点，但收口还是干净的；直接跟 bartender 说“想要松弛一点、好入口一点，但别太甜、别太随便”就够了。',
  },
  {
    id: 'ritual-not-fussy-reply',
    caseId: 'bar-expert-ritual-not-fussy',
    title: '仪式感靠到位，不靠隆重',
    text: '想喝得有仪式感，不等于第一杯就要很隆重、很费力。你可以先往 French 75、Champagne highball，或者干净一点的 aperitivo spritz 走，一上桌就有感觉，但不会把整晚点得太正式；直接跟 bartender 说“想要有点仪式感，但轻一点、别太累、别太隆重”就够了。',
  },
  {
    id: 'assertive-not-pushy-reply',
    caseId: 'bar-expert-assertive-not-pushy',
    title: '主见感靠边界，不靠命令',
    text: '想显得有主见一点，不是站在吧台前下指令。你可以直接跟 bartender 说“我想要偏干一点、基底清楚、别太甜的，你帮我从今天状态最稳的那杯里选一个”；这样方向是你给的，判断也很明确，但口气不会咄咄逼人。',
  },
  {
    id: 'crisp-not-harsh-cold-reply',
    caseId: 'bar-expert-crisp-not-harsh-cold',
    title: '利落感靠线条，不靠发硬',
    text: '想喝得利落一点，不等于第一杯就要很硬很冷。你可以先往 Gin Rickey、Tom Collins，或者干净一点的 Daiquiri 走，整体线条会更清楚、收口也快，但不会显得太冲；直接跟 bartender 说“想要利落一点、干净一点，但别太硬、别太冷”就够了。',
  },
  {
    id: 'soft-not-mushy-sweet-reply',
    caseId: 'bar-expert-soft-not-mushy-sweet',
    title: '柔和感靠收圆，不靠发甜',
    text: '想喝得柔和一点，不等于把第一杯点成很软很甜的东西。你可以先往 Whisky Sour、Southside，或者一杯酸度收一收的 Gin Sour 走，口感会更圆一点、顺一点，但骨架还在；直接跟 bartender 说“想要柔和一点、口感圆一点，但别太甜、别太软”就够了。',
  },
  {
    id: 'lively-not-too-loud-reply',
    caseId: 'bar-expert-lively-not-too-loud',
    title: '热闹感靠提气，不靠炸场',
    text: '想喝得热闹一点，不等于第一杯就要又甜又炸。你可以先往 Paloma、Hugo spritz，或者轻一点的 Moscow Mule 走，气泡、柑橘和香草感会把场子提起来，但不会一下把你推太快；直接跟 bartender 说“想要热闹一点、活一点，但别太甜、别太炸”就够了。',
  },
  {
    id: 'quiet-not-boring-reply',
    caseId: 'bar-expert-quiet-not-boring',
    title: '安静感靠低声部，不靠发闷',
    text: '想喝得安静一点，不等于把第一杯点成很平很闷的东西。你可以先往 Americano、竹子型 highball，或者轻一点的 aperitivo 走，整体会更安静、收口也稳，但不会无聊；直接跟 bartender 说“想要安静一点、低一点，但别太闷、别太没存在感”就够了。',
  },
  {
    id: 'light-not-thin-hollow-reply',
    caseId: 'bar-expert-light-not-thin-hollow',
    title: '轻盈感靠提起来，不靠发薄',
    text: '想喝得轻盈一点，不等于把第一杯点成很薄很空的东西。你可以先往 Tom Collins、Gin Fizz，或者骨架还在的轻一点 spritz 走，整体会更提一点、更透一点，但不会像只剩水感；直接跟 bartender 说“想要轻盈一点、往上提一点，但别太薄、别太空”就够了。',
  },
  {
    id: 'layered-not-heavy-oppressive-reply',
    caseId: 'bar-expert-layered-not-heavy-oppressive',
    title: '层次感靠展开，不靠压下来',
    text: '想喝得有层次一点，不等于第一杯就要很厚很重。你可以先往 Bamboo、Adonis，或者一杯展开感好的 Sherry Cobbler 走，香气和结构会更铺开一点，但不会压到你；直接跟 bartender 说“想要有层次一点、展开一点，但别太重、别太压人”就够了。',
  },
  {
    id: 'clean-not-sterile-alcohol-line-reply',
    caseId: 'bar-expert-clean-not-sterile-alcohol-line',
    title: '干净感靠线条清楚，不靠发寡',
    text: '想喝得干净一点，不等于把第一杯点成很寡很硬、像只剩酒精线条的东西。你可以先往 Gin Sonic、Whisky Highball，或者一杯做得干净的 Daiquiri 走，整体线条会更清楚、风味也更干净，但不会只剩酒精感；直接跟 bartender 说“想要干净一点、线条清楚一点，但别太寡、别太像只剩酒精线条”就够了。',
  },
  {
    id: 'rounded-not-creamy-cloying-reply',
    caseId: 'bar-expert-rounded-not-creamy-cloying',
    title: '圆润感靠收圆，不靠奶腻',
    text: '想喝得圆润一点，不等于把第一杯点成很奶很腻的东西。你可以先往 Pisco Sour、Bee\'s Knees，或者一杯收得干净的 Clover Club 走，口感会更顺一点、更圆一点，但不会像甜品；直接跟 bartender 说“想要圆润一点、顺一点，但别太奶、别太腻”就够了。',
  },
  {
    id: 'loose-not-scattered-boneless-reply',
    caseId: 'bar-expert-loose-not-scattered-boneless',
    title: '松感靠打开，不靠散架',
    text: '想喝得松一点，不等于把第一杯点成很散很水、没什么骨架的东西。你可以先往 Cynar & Soda、Sherry & Tonic，或者一杯更有轮廓的 Bamboo Highball 走，整体会更打开一点、更松一点，但骨架还在；直接跟 bartender 说“想要松一点、打开一点，但别太散、别太没骨架”就够了。',
  },
  {
    id: 'bright-not-sharp-harsh-reply',
    caseId: 'bar-expert-bright-not-sharp-harsh',
    title: '亮感靠提气，不靠发尖',
    text: '想喝得亮一点，不等于把第一杯点成很尖很冲、酸度顶很前的东西。你可以先往 Southside、White Port & Tonic，或者一杯带柑橘 lift 的 Gin Highball 走，整体会更亮一点、更提一点，但不会扎口；直接跟 bartender 说“想要亮一点、提一点，但别太尖、别太冲”就够了。',
  },
  {
    id: 'steady-not-boring-too-safe-reply',
    caseId: 'bar-expert-steady-not-boring-too-safe',
    title: '稳感靠落点，不靠保底',
    text: '想喝得稳一点，不等于把第一杯点成最无聊、最保险的东西。你可以先往 Whisky Highball、Paloma，或者一杯结构清楚的 Tommy\'s Margarita 走，整体会更有把握、也更好落地，但不会像在做最保守的选择；直接跟 bartender 说“想要稳一点、好入口一点，但别太无聊、别太像保底”就够了。',
  },
  {
    id: 'finish-clean-not-thin-short-reply',
    caseId: 'bar-expert-finish-clean-not-thin-short',
    title: '收口利落靠干净，不靠发空',
    text: '想喝得收口利落一点，不等于把第一杯点成很薄很短的东西。你可以先往 Americano、El Presidente，或者一杯收得干净的 Bamboo 走，整体会更利落一点、不拖，但中段不会一下空掉；直接跟 bartender 说“想要收口利落一点，但别太薄、别太短”就够了。',
  },
  {
    id: 'presence-not-too-full-heavy-reply',
    caseId: 'bar-expert-presence-not-too-full-heavy',
    title: '存在感靠轮廓，不靠发满',
    text: '想喝得有存在感一点，不等于把第一杯点成很满很撑的东西。你可以先往 Americano、Campari & Soda，或者一杯轮廓更清楚的 Paloma 走，整体会更有边缘、更立得住，但不会压得太满；直接跟 bartender 说“想要有存在感一点，但别太满、别太撑”就够了。',
  },
  {
    id: 'thick-not-dull-dragging-reply',
    caseId: 'bar-expert-thick-not-dull-dragging',
    title: '厚感靠中段，不靠拖尾',
    text: '想喝得厚一点，不等于把第一杯点成又闷又拖的东西。你可以先往 Martinez、Aged Rum Daiquiri，或者一杯收尾更利落的 Perfect Manhattan 走，中段会更有重量一点，但尾巴不会黏着不走；直接跟 bartender 说“想要厚一点、有点重量，但别太闷、别太拖”就够了。',
  },
  {
    id: 'fine-not-light-gripless-reply',
    caseId: 'bar-expert-fine-not-light-gripless',
    title: '细感靠线条，不靠发轻',
    text: '想喝得细一点，不等于把第一杯点成很轻很淡、没什么抓手的东西。你可以先往 Tuxedo No.2、50/50 Martini，或者一杯线条更细的 White Negroni 走，整体会更精一点、更细一点，但口感还是抓得住；直接跟 bartender 说“想要细一点、线条细一点，但别太轻、别太没抓手”就够了。',
  },
  {
    id: 'upright-not-hard-straight-reply',
    caseId: 'bar-expert-upright-not-hard-straight',
    title: '挺感靠骨架，不靠发硬',
    text: '想喝得挺一点，不等于把第一杯点成很硬很直、没什么缓冲的东西。你可以先往 50/50 Martini、Bamboo，或者一杯骨架更立的 Reverse Manhattan 走，整体会更挺一点、更站得住，但不会太直；直接跟 bartender 说“想要挺一点、骨架立一点，但别太硬、别太直”就够了。',
  },
  {
    id: 'plush-not-sticky-muddy-reply',
    caseId: 'bar-expert-plush-not-sticky-muddy',
    title: '糯感靠质地，不靠发糊',
    text: '想喝得糯一点，不等于把第一杯点成很黏很糊的东西。你可以先往 Japanese Cocktail、Gold Rush，或者一杯收得更干净的 Sidecar 走，口感会更贴一点、更有 texture，但不会糊成一团；直接跟 bartender 说“想要糯一点、口感贴一点，但别太黏、别太糊”就够了。',
  },
  {
    id: 'silky-not-oily-greasy-reply',
    caseId: 'bar-expert-silky-not-oily-greasy',
    title: '滑感靠细顺，不靠发油',
    text: '想喝得滑一点，不等于把第一杯点成很油很腻的东西。你可以先往 White Lady、Silver Fizz，或者一杯打得更细的 Pisco Sour 走，口感会更滑一点、更顺一点，但不会油着不走；直接跟 bartender 说“想要滑一点、顺一点，但别太油、别太腻”就够了。',
  },
  {
    id: 'pillowy-not-dull-muted-reply',
    caseId: 'bar-expert-pillowy-not-dull-muted',
    title: '绵感靠蓬松，不靠发闷',
    text: '想喝得绵一点，不等于把第一杯点成很钝很闷、像把味道捂住的东西。你可以先往 Ramos Gin Fizz、Clover Club，或者一杯泡沫打得更细的 Whisky Sour 走，口感会更绵一点、更蓬一点，但不会闷成一团；直接跟 bartender 说“想要绵一点、柔一点，但别太钝、别太闷”就够了。',
  },
  {
    id: 'bouncy-not-jumpy-sharp-reply',
    caseId: 'bar-expert-bouncy-not-jumpy-sharp',
    title: '弹感靠提劲，不靠发尖',
    text: '想喝得弹一点，不等于把第一杯点成又跳又尖、一下子往前冲的东西。你可以先往 Gin Sonic、Ranch Water，或者一杯气泡更细的 Gin Fizz 走，口感会更弹一点、更往上提一点，但不会尖得扎口；直接跟 bartender 说“想要弹一点、提一点，但别太跳、别太尖”就够了。',
  },
  {
    id: 'supple-not-muddy-dragging-reply',
    caseId: 'bar-expert-supple-not-muddy-dragging',
    title: '润感靠中段，不靠发拖',
    text: '想喝得润一点，不等于把第一杯点成很糊很拖、尾巴黏着不走的东西。你可以先往 Tommy\'s Margarita、Eastside，或者一杯收得更干净的 White Lady 走，中段会更润一点、更顺一点，但不会糊在嘴里；直接跟 bartender 说“想要润一点、顺一点，但别太糊、别太拖”就够了。',
  },
  {
    id: 'snappy-not-thin-sharp-reply',
    caseId: 'bar-expert-snappy-not-thin-sharp',
    title: '脆感靠咬口，不靠发薄',
    text: '想喝得脆一点，不等于把第一杯点成很薄很尖、线条直接刮上来的东西。你可以先往 Whisky Highball、Gin Buck，或者一杯轮廓更清楚的 Paloma 走，入口会更脆一点、更有咬口，但不会尖得发空；直接跟 bartender 说“想要脆一点、咬口清楚一点，但别太薄、别太尖”就够了。',
  },
  {
    id: 'uplifted-not-hard-harsh-reply',
    caseId: 'bar-expert-uplifted-not-hard-harsh',
    title: '挺拔感靠提线，不靠发硬',
    text: '想喝得挺拔一点，不等于把第一杯点成很硬很冲、边缘直接顶上来的东西。你可以先往 Gin & Tonic、White Port & Tonic，或者一杯线条更往上提的 Bamboo Highball 走，整体会更挺拔一点、更站得住，但不会硬得发顶；直接跟 bartender 说“想要挺拔一点、线条往上提一点，但别太硬、别太冲”就够了。',
  },
  {
    id: 'open-bright-not-floaty-hollow-reply',
    caseId: 'bar-expert-open-bright-not-floaty-hollow',
    title: '松亮感靠打开，不靠发空',
    text: '想喝得松亮一点，不等于把第一杯点成很飘很空、像只剩亮点浮在上面的东西。你可以先往 Aperol Spritz、White Port & Tonic，或者一杯更打开的 Sherry & Tonic 走，整体会更松亮一点、更透一点，但中段不会空掉；直接跟 bartender 说“想要松亮一点、打开一点，但别太飘、别太空”就够了。',
  },
  {
    id: 'tight-not-tense-hard-reply',
    caseId: 'bar-expert-tight-not-tense-hard',
    title: '紧感靠收束，不靠发绷',
    text: '想喝得紧一点，不等于把第一杯点成很绷很硬、边缘拉太满的东西。你可以先往 Daiquiri、Tommy\'s Margarita，或者一杯结构更收的 Bamboo 走，整体会更紧一点、更利落一点，但不会绷在脸上；直接跟 bartender 说“想要紧一点、结构收一点，但别太绷、别太硬”就够了。',
  },
  {
    id: 'relaxed-round-not-soft-flat-reply',
    caseId: 'bar-expert-relaxed-round-not-soft-flat',
    title: '松弛圆感靠托住，不靠发塌',
    text: '想喝得松弛圆一点，不等于把第一杯点成很软很塌、中段直接坐下去的东西。你可以先往 Adonis、Sherry Cobbler，或者一杯更松一点的 Americano 走，整体会更圆一点、更放松一点，但不会软到没支撑；直接跟 bartender 说“想要松弛圆一点、顺一点，但别太软、别太塌”就够了。',
  },
  {
    id: 'clean-cut-not-thin-cutting-reply',
    caseId: 'bar-expert-clean-cut-not-thin-cutting',
    title: '干脆感靠落点，不靠削薄',
    text: '想喝得干脆一点，不等于把第一杯点成很薄很利、像边缘被削得太尖的东西。你可以先往 Gin Sonic、Bamboo，或者一杯更收得利落的 El Presidente 走，整体会更干脆一点、落点更清楚一点，但不会薄到只剩线条；直接跟 bartender 说“想要干脆一点、干净一点，但别太薄、别太利”就够了。',
  },
  {
    id: 'help-friend-order-no-pressure-reply',
    caseId: 'bar-expert-help-friend-order-no-pressure',
    title: '帮朋友点酒别点成展示题',
    text: '你别替他点成展示题，替他把门槛降下来就行。可以直接跟 bartender 说“这是朋友第一次来，想要清一点、不苦、酒精感别太重，给一杯好入口的”；这样既不会让他在酒单前发愣，也不会显得你在替他装懂。',
  },
  {
    id: 'first-drink-recovery-second-order-reply',
    caseId: 'bar-expert-first-drink-recovery-second-order',
    title: '第一杯点错就礼貌纠偏',
    text: '不用硬撑着喝完。你可以直接跟 bartender 说“这杯方向我喝下来有点不对口，下一杯想清一点、别这么苦/甜/重”，这已经很礼貌了；重点不是解释自己多懂，是把不喜欢的点说清，第二杯往更稳、更接近你口味的方向修正。',
  },
  {
    id: 'tipsy-stop-gracefully-reply',
    caseId: 'bar-expert-tipsy-stop-gracefully',
    title: '微醺后体面收口',
    text: '这时候就别再继续加酒了，体面不是硬撑。你可以直接跟 bartender 说“我后面想收一下，先来杯水或者一杯不带酒精、别太甜的”，手里有杯东西，场面也不会尴尬；真有人继续劝，你就说已经到刚好的点了。',
  },
  {
    id: 'second-round-dont-push-night-reply',
    caseId: 'bar-expert-second-round-dont-push-night',
    title: '第二杯别默认往上加码',
    text: '第二杯最稳的接法，通常不是往上加码，而是平着走或者往下收一点。你第一杯如果是 Gin Rickey，第二杯可以继续 highball 系，或者换成更轻一点的 spritz、Americano；直接跟 bartender 说“想续一杯，但别把后半夜推太快”，这句就够用了。',
  },
  {
    id: 'drink-spiking-safety-reply',
    caseId: 'bar-expert-drink-spiking-safety',
    title: '怀疑被动手脚时的安全回复',
    text: '先别让她再喝，也别让她一个人待着。把那杯留着，立刻叫店员或安保过来，找一个清醒朋友一起把她带到明亮安全的地方；如果已经站不稳、意识发飘、异常困倦，直接打急救或马上送医。现在先保人和证据，别继续纠结那杯到底是什么。',
  },
];
