import { describe, expect, it } from "vitest";
import {
  ADMIN_SESSION_PAGE_SIZE_OPTIONS,
  ADMIN_SESSION_REASON_FILTERS,
  ADMIN_SESSION_SCOPE_FILTERS,
  ADMIN_SESSION_SORT_DIRECTIONS,
  ADMIN_SESSION_SORT_FIELDS,
  ADMIN_SESSION_SOURCE_GROUP_PAGE_SIZE_OPTIONS,
  ADMIN_SESSION_SOURCE_GROUP_RISK_LEVELS,
  ADMIN_SESSION_SOURCE_GROUP_SORT_DIRECTIONS,
  ADMIN_SESSION_SOURCE_GROUP_SORT_FIELDS,
  ADMIN_SESSION_STATUS_FILTERS,
  buildAdminSessionsPermalink,
  buildCompactAdminSessionsRouteSearch,
  buildAdminSessionsRouteSearch,
  DEFAULT_ADMIN_SESSIONS_ROUTE_SEARCH,
  validateAdminSessionsRouteSearch,
} from "../src/lib/admin-sessions-route-search";
import {
  defineRouteSearchNormalizationTests,
  defineRouteSearchStaticContractTest,
} from "./route-search-test-helpers";

describe("admin sessions route search", () => {
  defineRouteSearchStaticContractTest({
    description:
      "keeps filter, sort, and page-size option ordering aligned with the default route search",
    expectations: [
      {
        description: "session status filters stay in their expected display order",
        actual: ADMIN_SESSION_STATUS_FILTERS,
        expected: ["all", "active", "expired", "revoked"],
      },
      {
        description: "revocation reason filters stay in their expected display order",
        actual: ADMIN_SESSION_REASON_FILTERS,
        expected: ["all", "logout", "manual-revocation", "refresh-token-reuse"],
      },
      {
        description: "scope filters stay in their expected display order",
        actual: ADMIN_SESSION_SCOPE_FILTERS,
        expected: ["all", "current"],
      },
      {
        description: "session sort fields stay in their expected display order",
        actual: ADMIN_SESSION_SORT_FIELDS,
        expected: ["updatedAt", "createdAt", "expiresAt", "lastUsedAt", "revokedAt"],
      },
      {
        description: "session sort directions stay in their expected display order",
        actual: ADMIN_SESSION_SORT_DIRECTIONS,
        expected: ["desc", "asc"],
      },
      {
        description: "source-group sort fields stay in their expected display order",
        actual: ADMIN_SESSION_SOURCE_GROUP_SORT_FIELDS,
        expected: [
          "activeSessions",
          "totalSessions",
          "latestLastUsedAt",
          "latestCreatedAt",
          "latestRevokedAt",
        ],
      },
      {
        description: "source-group sort directions stay in their expected display order",
        actual: ADMIN_SESSION_SOURCE_GROUP_SORT_DIRECTIONS,
        expected: ["desc", "asc"],
      },
      {
        description: "source-group risk levels stay in their expected display order",
        actual: ADMIN_SESSION_SOURCE_GROUP_RISK_LEVELS,
        expected: ["all", "critical", "watch", "normal"],
      },
      {
        description: "session page-size options stay in their expected display order",
        actual: ADMIN_SESSION_PAGE_SIZE_OPTIONS,
        expected: [10, 20, 50],
      },
      {
        description:
          "source-group page-size options stay in their expected display order",
        actual: ADMIN_SESSION_SOURCE_GROUP_PAGE_SIZE_OPTIONS,
        expected: [6, 12, 24],
      },
      {
        description: "default admin-sessions route search stays stable",
        actual: DEFAULT_ADMIN_SESSIONS_ROUTE_SEARCH,
        expected: {
          status: "all",
          revocationReason: "all",
          scope: "all",
          query: "",
          sourceKey: "",
          sourceIssuedFromIp: "",
          sourceIssuedUserAgent: "",
          sortBy: "updatedAt",
          sortDirection: "desc",
          page: 1,
          pageSize: 10,
          sourceSortBy: "activeSessions",
          sourceSortDirection: "desc",
          sourceRiskLevel: "all",
          sourcePage: 1,
          sourcePageSize: 6,
        },
      },
    ],
  });

  defineRouteSearchNormalizationTests({
    build: buildAdminSessionsRouteSearch,
    validate: validateAdminSessionsRouteSearch,
    validBuildCases: [
      {
        description:
          "trim valid admin-session filters and parse valid pagination fields",
        input: {
          status: " active ",
          revocationReason: " manual-revocation ",
          scope: " current ",
          query: "  admin@example.com  ",
          sourceKey: "  browser:chrome  ",
          sourceIssuedFromIp: "  127.0.0.1  ",
          sourceIssuedUserAgent: "  Mozilla/5.0  ",
          sortBy: " expiresAt ",
          sortDirection: " asc ",
          page: " 3 ",
          pageSize: " 20 ",
          sourceSortBy: " latestRevokedAt ",
          sourceSortDirection: " asc ",
          sourceRiskLevel: " critical ",
          sourcePage: " 4 ",
          sourcePageSize: " 12 ",
        },
        expected: {
          status: "active",
          revocationReason: "manual-revocation",
          scope: "current",
          query: "  admin@example.com  ",
          sourceKey: "browser:chrome",
          sourceIssuedFromIp: "127.0.0.1",
          sourceIssuedUserAgent: "Mozilla/5.0",
          sortBy: "expiresAt",
          sortDirection: "asc",
          page: 3,
          pageSize: 20,
          sourceSortBy: "latestRevokedAt",
          sourceSortDirection: "asc",
          sourceRiskLevel: "critical",
          sourcePage: 4,
          sourcePageSize: 12,
        },
      },
    ],
    invalidBuildCases: [
      {
        description: "fall back for invalid filters, sorts, and page-size options",
        input: {
          status: "pending",
          revocationReason: "system",
          scope: "mine",
          query: 123,
          sourceKey: null,
          sourceIssuedFromIp: false,
          sourceIssuedUserAgent: {},
          sortBy: "provider",
          sortDirection: "down",
          page: "0",
          pageSize: 13,
          sourceSortBy: "latestIssuedAt",
          sourceSortDirection: "up",
          sourceRiskLevel: "urgent",
          sourcePage: -1,
          sourcePageSize: 7,
        },
        expected: DEFAULT_ADMIN_SESSIONS_ROUTE_SEARCH,
      },
      {
        description: "fall back when no route search is provided",
        input: undefined,
        expected: DEFAULT_ADMIN_SESSIONS_ROUTE_SEARCH,
      },
    ],
    validateCases: [
      {
        description: "keep valid validated admin-session filters",
        input: {
          status: "revoked",
          revocationReason: "refresh-token-reuse",
          scope: "all",
          query: "keep raw query",
          sourceKey: "vpn:office",
          sourceIssuedFromIp: "10.0.0.8",
          sourceIssuedUserAgent: "CLI",
          sortBy: "revokedAt",
          sortDirection: "asc",
          page: "2",
          pageSize: "50",
          sourceSortBy: "totalSessions",
          sourceSortDirection: "asc",
          sourceRiskLevel: "watch",
          sourcePage: "3",
          sourcePageSize: "24",
          ignored: "value",
        },
        expected: {
          status: "revoked",
          revocationReason: "refresh-token-reuse",
          scope: "all",
          query: "keep raw query",
          sourceKey: "vpn:office",
          sourceIssuedFromIp: "10.0.0.8",
          sourceIssuedUserAgent: "CLI",
          sortBy: "revokedAt",
          sortDirection: "asc",
          page: 2,
          pageSize: 50,
          sourceSortBy: "totalSessions",
          sourceSortDirection: "asc",
          sourceRiskLevel: "watch",
          sourcePage: 3,
          sourcePageSize: 24,
        },
      },
      {
        description:
          "trim valid admin-session filters and default invalid validated values",
        input: {
          status: " expired ",
          revocationReason: "",
          scope: undefined,
          query: undefined,
          sourceKey: "  ",
          sourceIssuedFromIp: null,
          sourceIssuedUserAgent: false,
          sortBy: "",
          sortDirection: "",
          page: "nope",
          pageSize: "15",
          sourceSortBy: "",
          sourceSortDirection: "",
          sourceRiskLevel: "",
          sourcePage: "0",
          sourcePageSize: "18",
        },
        expected: {
          ...DEFAULT_ADMIN_SESSIONS_ROUTE_SEARCH,
          status: "expired",
        },
      },
    ],
  });

  it("builds compact admin-sessions route search and permalink", () => {
    expect(
      buildCompactAdminSessionsRouteSearch(DEFAULT_ADMIN_SESSIONS_ROUTE_SEARCH),
    ).toEqual({});

    expect(
      buildCompactAdminSessionsRouteSearch({
        status: "revoked",
        revocationReason: "manual-revocation",
        scope: "current",
        query: "admin@example.com",
        sourceKey: "browser:chrome",
        sourceIssuedFromIp: "10.0.0.8",
        sourceIssuedUserAgent: "Mozilla/5.0",
        sortBy: "revokedAt",
        sortDirection: "asc",
        page: 2,
        pageSize: 20,
        sourceSortBy: "totalSessions",
        sourceSortDirection: "asc",
        sourceRiskLevel: "watch",
        sourcePage: 3,
        sourcePageSize: 12,
      }),
    ).toEqual({
      status: "revoked",
      revocationReason: "manual-revocation",
      scope: "current",
      query: "admin@example.com",
      sourceKey: "browser:chrome",
      sourceIssuedFromIp: "10.0.0.8",
      sourceIssuedUserAgent: "Mozilla/5.0",
      sortBy: "revokedAt",
      sortDirection: "asc",
      page: 2,
      pageSize: 20,
      sourceSortBy: "totalSessions",
      sourceSortDirection: "asc",
      sourceRiskLevel: "watch",
      sourcePage: 3,
      sourcePageSize: 12,
    });

    expect(
      buildAdminSessionsPermalink({
        status: "revoked",
        revocationReason: "manual-revocation",
        scope: "current",
        query: "admin@example.com",
        sourceKey: "browser:chrome",
        sourceIssuedFromIp: "10.0.0.8",
        sourceIssuedUserAgent: "Mozilla/5.0",
        sortBy: "revokedAt",
        sortDirection: "asc",
        page: 2,
        pageSize: 20,
        sourceSortBy: "totalSessions",
        sourceSortDirection: "asc",
        sourceRiskLevel: "watch",
        sourcePage: 3,
        sourcePageSize: 12,
      }),
    ).toBe(
      "/sessions?status=revoked&revocationReason=manual-revocation&scope=current&query=admin%40example.com&sourceKey=browser%3Achrome&sourceIssuedFromIp=10.0.0.8&sourceIssuedUserAgent=Mozilla%2F5.0&sortBy=revokedAt&sortDirection=asc&page=2&pageSize=20&sourceSortBy=totalSessions&sourceSortDirection=asc&sourceRiskLevel=watch&sourcePage=3&sourcePageSize=12",
    );
  });
});
