import { describe, expect, it } from "vitest";
import * as waitingSessionSyncControls from "../src/components/waiting-session-sync-controls";
import * as waitingSessionSyncFilterControls from "../src/components/waiting-session-sync-filter-controls";
import * as waitingSessionSyncFragments from "../src/components/waiting-session-sync-fragments";
import * as waitingSessionSyncArtifacts from "../src/lib/waiting-session-sync-artifacts";
import * as waitingSessionSyncCopy from "../src/lib/waiting-session-sync-copy";
import * as waitingSessionSyncHelpers from "../src/lib/waiting-session-sync-helpers";
import * as waitingSessionSyncNotices from "../src/lib/waiting-session-sync-notices";
import * as waitingSessionSyncRouteSearch from "../src/lib/waiting-session-sync-route-search";

describe("waiting session sync barrels", () => {
  it("keeps the waiting-session-sync-controls barrel aligned with shared waiting-session-sync components", () => {
    expect(Object.keys(waitingSessionSyncControls).sort()).toEqual([
      "WaitingSessionSyncActionAnchor",
      "WaitingSessionSyncActionButton",
      "WaitingSessionSyncArtifactSummary",
      "WaitingSessionSyncCountChip",
      "WaitingSessionSyncFilterControls",
      "WaitingSessionSyncPaginationControls",
      "WaitingSessionSyncStatusPills",
      "WaitingSessionSyncTaskStatusBadge",
      "getWaitingSessionSyncActionClassName",
      "getWaitingSessionSyncActionLinkClassName",
    ]);

    expect(waitingSessionSyncControls.WaitingSessionSyncActionAnchor).toBe(
      waitingSessionSyncFragments.WaitingSessionSyncActionAnchor,
    );
    expect(waitingSessionSyncControls.WaitingSessionSyncActionButton).toBe(
      waitingSessionSyncFragments.WaitingSessionSyncActionButton,
    );
    expect(waitingSessionSyncControls.WaitingSessionSyncArtifactSummary).toBe(
      waitingSessionSyncFragments.WaitingSessionSyncArtifactSummary,
    );
    expect(waitingSessionSyncControls.WaitingSessionSyncCountChip).toBe(
      waitingSessionSyncFragments.WaitingSessionSyncCountChip,
    );
    expect(waitingSessionSyncControls.WaitingSessionSyncFilterControls).toBe(
      waitingSessionSyncFilterControls.WaitingSessionSyncFilterControls,
    );
    expect(waitingSessionSyncControls.WaitingSessionSyncPaginationControls).toBe(
      waitingSessionSyncFilterControls.WaitingSessionSyncPaginationControls,
    );
    expect(waitingSessionSyncControls.WaitingSessionSyncStatusPills).toBe(
      waitingSessionSyncFragments.WaitingSessionSyncStatusPills,
    );
    expect(waitingSessionSyncControls.WaitingSessionSyncTaskStatusBadge).toBe(
      waitingSessionSyncFragments.WaitingSessionSyncTaskStatusBadge,
    );
    expect(
      waitingSessionSyncControls.getWaitingSessionSyncActionClassName,
    ).toBe(waitingSessionSyncFragments.getWaitingSessionSyncActionClassName);
    expect(
      waitingSessionSyncControls.getWaitingSessionSyncActionLinkClassName,
    ).toBe(waitingSessionSyncFragments.getWaitingSessionSyncActionLinkClassName);
  });

  it("keeps the waiting-session-sync-helpers barrel aligned with waiting-session-sync helper modules", () => {
    expect(Object.keys(waitingSessionSyncHelpers).sort()).toEqual([
      "DEFAULT_WAITING_SESSION_SYNC_ROUTE_SEARCH",
      "WAITING_SESSION_SYNC_PAGE_SIZE_OPTIONS",
      "WAITING_SESSION_SYNC_STATUS_FILTERS",
      "WAITING_SESSION_SYNC_TASK_TYPE_FILTERS",
      "buildWaitingSessionSyncArtifactFilename",
      "buildWaitingSessionSyncContextGroupsCsv",
      "buildWaitingSessionSyncContextReviewCopy",
      "buildWaitingSessionSyncPermalink",
      "buildWaitingSessionSyncRouteSearch",
      "buildWaitingSessionSyncSnapshotLookup",
      "buildWaitingSessionSyncTaskReviewCopy",
      "buildWaitingSessionSyncTasksCsv",
      "createWaitingSessionSyncClearTaskNotice",
      "createWaitingSessionSyncContextGroupsCsvNotice",
      "createWaitingSessionSyncContextGroupsSnapshotNotice",
      "createWaitingSessionSyncContextGroupsSnapshotPayload",
      "createWaitingSessionSyncContextSnapshotPayload",
      "createWaitingSessionSyncCopyNotice",
      "createWaitingSessionSyncFilteredClearNotice",
      "createWaitingSessionSyncFilteredReplayNotice",
      "createWaitingSessionSyncFilteredSnapshotPayload",
      "createWaitingSessionSyncFocusSnapshotPayload",
      "createWaitingSessionSyncReplayTaskNotice",
      "createWaitingSessionSyncSnapshotNotice",
      "describeWaitingSessionSyncBatchActionSummary",
      "describeWaitingSessionSyncFocusGuardCopy",
      "serializeWaitingSessionSyncContextGroupArtifact",
      "serializeWaitingSessionSyncSnapshotTask",
      "summarizeWaitingSessionSyncTasks",
      "validateWaitingSessionSyncRouteSearch",
    ]);

    expect(waitingSessionSyncHelpers.DEFAULT_WAITING_SESSION_SYNC_ROUTE_SEARCH).toBe(
      waitingSessionSyncRouteSearch.DEFAULT_WAITING_SESSION_SYNC_ROUTE_SEARCH,
    );
    expect(waitingSessionSyncHelpers.WAITING_SESSION_SYNC_PAGE_SIZE_OPTIONS).toBe(
      waitingSessionSyncRouteSearch.WAITING_SESSION_SYNC_PAGE_SIZE_OPTIONS,
    );
    expect(waitingSessionSyncHelpers.WAITING_SESSION_SYNC_STATUS_FILTERS).toBe(
      waitingSessionSyncRouteSearch.WAITING_SESSION_SYNC_STATUS_FILTERS,
    );
    expect(waitingSessionSyncHelpers.WAITING_SESSION_SYNC_TASK_TYPE_FILTERS).toBe(
      waitingSessionSyncRouteSearch.WAITING_SESSION_SYNC_TASK_TYPE_FILTERS,
    );
    expect(waitingSessionSyncHelpers.buildWaitingSessionSyncArtifactFilename).toBe(
      waitingSessionSyncCopy.buildWaitingSessionSyncArtifactFilename,
    );
    expect(waitingSessionSyncHelpers.buildWaitingSessionSyncContextGroupsCsv).toBe(
      waitingSessionSyncArtifacts.buildWaitingSessionSyncContextGroupsCsv,
    );
    expect(waitingSessionSyncHelpers.buildWaitingSessionSyncContextReviewCopy).toBe(
      waitingSessionSyncCopy.buildWaitingSessionSyncContextReviewCopy,
    );
    expect(waitingSessionSyncHelpers.buildWaitingSessionSyncPermalink).toBe(
      waitingSessionSyncCopy.buildWaitingSessionSyncPermalink,
    );
    expect(waitingSessionSyncHelpers.buildWaitingSessionSyncRouteSearch).toBe(
      waitingSessionSyncRouteSearch.buildWaitingSessionSyncRouteSearch,
    );
    expect(waitingSessionSyncHelpers.buildWaitingSessionSyncSnapshotLookup).toBe(
      waitingSessionSyncArtifacts.buildWaitingSessionSyncSnapshotLookup,
    );
    expect(waitingSessionSyncHelpers.buildWaitingSessionSyncTaskReviewCopy).toBe(
      waitingSessionSyncCopy.buildWaitingSessionSyncTaskReviewCopy,
    );
    expect(waitingSessionSyncHelpers.buildWaitingSessionSyncTasksCsv).toBe(
      waitingSessionSyncArtifacts.buildWaitingSessionSyncTasksCsv,
    );
    expect(waitingSessionSyncHelpers.createWaitingSessionSyncClearTaskNotice).toBe(
      waitingSessionSyncNotices.createWaitingSessionSyncClearTaskNotice,
    );
    expect(
      waitingSessionSyncHelpers.createWaitingSessionSyncContextGroupsCsvNotice,
    ).toBe(waitingSessionSyncNotices.createWaitingSessionSyncContextGroupsCsvNotice);
    expect(
      waitingSessionSyncHelpers.createWaitingSessionSyncContextGroupsSnapshotNotice,
    ).toBe(
      waitingSessionSyncNotices.createWaitingSessionSyncContextGroupsSnapshotNotice,
    );
    expect(
      waitingSessionSyncHelpers.createWaitingSessionSyncContextGroupsSnapshotPayload,
    ).toBe(
      waitingSessionSyncArtifacts.createWaitingSessionSyncContextGroupsSnapshotPayload,
    );
    expect(
      waitingSessionSyncHelpers.createWaitingSessionSyncContextSnapshotPayload,
    ).toBe(
      waitingSessionSyncArtifacts.createWaitingSessionSyncContextSnapshotPayload,
    );
    expect(waitingSessionSyncHelpers.createWaitingSessionSyncCopyNotice).toBe(
      waitingSessionSyncNotices.createWaitingSessionSyncCopyNotice,
    );
    expect(waitingSessionSyncHelpers.createWaitingSessionSyncFilteredClearNotice).toBe(
      waitingSessionSyncNotices.createWaitingSessionSyncFilteredClearNotice,
    );
    expect(waitingSessionSyncHelpers.createWaitingSessionSyncFilteredReplayNotice).toBe(
      waitingSessionSyncNotices.createWaitingSessionSyncFilteredReplayNotice,
    );
    expect(
      waitingSessionSyncHelpers.createWaitingSessionSyncFilteredSnapshotPayload,
    ).toBe(waitingSessionSyncArtifacts.createWaitingSessionSyncFilteredSnapshotPayload);
    expect(waitingSessionSyncHelpers.createWaitingSessionSyncFocusSnapshotPayload).toBe(
      waitingSessionSyncArtifacts.createWaitingSessionSyncFocusSnapshotPayload,
    );
    expect(waitingSessionSyncHelpers.createWaitingSessionSyncReplayTaskNotice).toBe(
      waitingSessionSyncNotices.createWaitingSessionSyncReplayTaskNotice,
    );
    expect(waitingSessionSyncHelpers.createWaitingSessionSyncSnapshotNotice).toBe(
      waitingSessionSyncNotices.createWaitingSessionSyncSnapshotNotice,
    );
    expect(
      waitingSessionSyncHelpers.describeWaitingSessionSyncBatchActionSummary,
    ).toBe(waitingSessionSyncCopy.describeWaitingSessionSyncBatchActionSummary);
    expect(waitingSessionSyncHelpers.describeWaitingSessionSyncFocusGuardCopy).toBe(
      waitingSessionSyncCopy.describeWaitingSessionSyncFocusGuardCopy,
    );
    expect(
      waitingSessionSyncHelpers.serializeWaitingSessionSyncContextGroupArtifact,
    ).toBe(waitingSessionSyncArtifacts.serializeWaitingSessionSyncContextGroupArtifact);
    expect(waitingSessionSyncHelpers.serializeWaitingSessionSyncSnapshotTask).toBe(
      waitingSessionSyncArtifacts.serializeWaitingSessionSyncSnapshotTask,
    );
    expect(waitingSessionSyncHelpers.summarizeWaitingSessionSyncTasks).toBe(
      waitingSessionSyncArtifacts.summarizeWaitingSessionSyncTasks,
    );
    expect(waitingSessionSyncHelpers.validateWaitingSessionSyncRouteSearch).toBe(
      waitingSessionSyncRouteSearch.validateWaitingSessionSyncRouteSearch,
    );
  });
});
