type SeedEntry = {
  id: string;
  label: string;
  vendor: string;
  providerFamily: string;
  region: 'global' | 'domestic';
  status: 'active' | 'preview' | 'legacy';
  supportsVision?: boolean;
  supportsAudio?: boolean;
  supportsReasoning?: boolean;
  defaultAvatar: string;
  rolePromptHint: string;
  description: string;
};

const MODEL_SEED_ENTRIES: SeedEntry[] = [
  {
    id: 'gpt-4.1',
    label: 'GPT-4.1',
    vendor: 'OpenAI',
    providerFamily: 'openai',
    region: 'global',
    status: 'active',
    supportsVision: true,
    defaultAvatar: '🧠',
    rolePromptHint: '长文本稳定、表达克制、偏通才型。',
    description: 'OpenAI 通用旗舰模型，适合作为冷静、稳健的综合型角色。',
  },
  {
    id: 'gpt-4.1-mini',
    label: 'GPT-4.1 Mini',
    vendor: 'OpenAI',
    providerFamily: 'openai',
    region: 'global',
    status: 'active',
    supportsVision: true,
    defaultAvatar: '⚙️',
    rolePromptHint: '反应快、成本友好、适合高频互动。',
    description: 'OpenAI 轻量高频模型，适合作为高活跃、短回复角色。',
  },
  {
    id: 'gpt-4o',
    label: 'GPT-4o',
    vendor: 'OpenAI',
    providerFamily: 'openai',
    region: 'global',
    status: 'active',
    supportsVision: true,
    supportsAudio: true,
    defaultAvatar: '🎛️',
    rolePromptHint: '多模态感强、聊天自然、适合现场感角色。',
    description: 'OpenAI 多模态主力模型，适合视频、语音和图文混合角色。',
  },
  {
    id: 'gpt-4o-mini',
    label: 'GPT-4o Mini',
    vendor: 'OpenAI',
    providerFamily: 'openai',
    region: 'global',
    status: 'active',
    supportsVision: true,
    supportsAudio: true,
    defaultAvatar: '📻',
    rolePromptHint: '轻盈、响应快、适合移动端高频会话。',
    description: 'OpenAI 轻量多模态模型，适合陪聊和实时互动角色。',
  },
  {
    id: 'gpt-5',
    label: 'GPT-5',
    vendor: 'OpenAI',
    providerFamily: 'openai',
    region: 'global',
    status: 'active',
    supportsVision: true,
    supportsReasoning: true,
    defaultAvatar: '🪐',
    rolePromptHint: '更强规划和抽象能力，适合作为高阶策划型角色。',
    description: 'OpenAI 新一代旗舰推理模型，适合作为重规划、重分析角色。',
  },
  {
    id: 'o1',
    label: 'o1',
    vendor: 'OpenAI',
    providerFamily: 'openai',
    region: 'global',
    status: 'legacy',
    supportsReasoning: true,
    defaultAvatar: '🧩',
    rolePromptHint: '深度推理、结论审慎、节奏偏慢。',
    description: 'OpenAI 早期推理系模型，适合作为慎重、慢热型角色。',
  },
  {
    id: 'o3',
    label: 'o3',
    vendor: 'OpenAI',
    providerFamily: 'openai',
    region: 'global',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '🛰️',
    rolePromptHint: '推理重、判断硬、适合策略和诊断型角色。',
    description: 'OpenAI 强推理模型，适合作为策略顾问、分析师角色。',
  },
  {
    id: 'o4-mini-all',
    label: 'o4-mini-all',
    vendor: 'OpenAI',
    providerFamily: 'openai',
    region: 'global',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '🔬',
    rolePromptHint: '推理轻快、偏工程执行型。',
    description: 'OpenAI 轻量推理模型，适合作为执行型、技术型角色。',
  },
  {
    id: 'claude-opus-4-20250514',
    label: 'Claude Opus 4',
    vendor: 'Anthropic',
    providerFamily: 'anthropic',
    region: 'global',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '🪶',
    rolePromptHint: '审美和表达感强，适合深谈、写作与复杂判断。',
    description: 'Anthropic 重质感旗舰模型，适合作为成熟、深谈型角色。',
  },
  {
    id: 'claude-sonnet-4-5',
    label: 'Claude Sonnet 4.5',
    vendor: 'Anthropic',
    providerFamily: 'anthropic',
    region: 'global',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '📚',
    rolePromptHint: '表达平衡、文风稳定、推理和可读性兼顾。',
    description: 'Anthropic 通用主力模型，适合作为顾问、创作型角色。',
  },
  {
    id: 'claude-haiku-4-5-20251001-thinking',
    label: 'Claude Haiku 4.5 Thinking',
    vendor: 'Anthropic',
    providerFamily: 'anthropic',
    region: 'global',
    status: 'preview',
    supportsReasoning: true,
    defaultAvatar: '🍃',
    rolePromptHint: '轻快、短句、机敏，适合作为高频小陪伴角色。',
    description: 'Anthropic 轻量思考模型，适合作为节奏快、回复短的角色。',
  },
  {
    id: 'gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    vendor: 'Google',
    providerFamily: 'google',
    region: 'global',
    status: 'active',
    supportsVision: true,
    supportsAudio: true,
    supportsReasoning: true,
    defaultAvatar: '🌈',
    rolePromptHint: '多模态、资料整合和长上下文能力强。',
    description: 'Google 多模态旗舰模型，适合作为研究型、情境感强角色。',
  },
  {
    id: 'gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    vendor: 'Google',
    providerFamily: 'google',
    region: 'global',
    status: 'active',
    supportsVision: true,
    supportsAudio: true,
    defaultAvatar: '⚡',
    rolePromptHint: '速度快、适合连续多轮互动和工具反馈。',
    description: 'Google 轻量多模态模型，适合作为即时反馈型角色。',
  },
  {
    id: 'grok-4.1',
    label: 'Grok 4.1',
    vendor: 'xAI',
    providerFamily: 'xai',
    region: 'global',
    status: 'active',
    supportsVision: true,
    supportsReasoning: true,
    defaultAvatar: '🚀',
    rolePromptHint: '锋利、直接、信息密度高。',
    description: 'xAI 主力模型，适合作为观点鲜明、风格直接的角色。',
  },
  {
    id: 'grok-4.1-fast',
    label: 'Grok 4.1 Fast',
    vendor: 'xAI',
    providerFamily: 'xai',
    region: 'global',
    status: 'active',
    supportsVision: true,
    defaultAvatar: '⚡',
    rolePromptHint: '更激进、节奏更快、适合热场型角色。',
    description: 'xAI 轻快版本，适合作为高反应、强存在感角色。',
  },
  {
    id: 'deepseek-chat',
    label: 'DeepSeek Chat',
    vendor: 'DeepSeek',
    providerFamily: 'deepseek',
    region: 'domestic',
    status: 'active',
    defaultAvatar: '🌊',
    rolePromptHint: '中文自然、性价比高、适合作为常驻聊天角色。',
    description: 'DeepSeek 通用模型，适合作为高频中文对话角色。',
  },
  {
    id: 'deepseek-r1',
    label: 'DeepSeek R1',
    vendor: 'DeepSeek',
    providerFamily: 'deepseek',
    region: 'domestic',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '🧮',
    rolePromptHint: '推理长、链路重，适合作为冷静分析型角色。',
    description: 'DeepSeek 推理模型，适合作为思辨、拆解问题的角色。',
  },
  {
    id: 'deepseek-v3',
    label: 'DeepSeek V3',
    vendor: 'DeepSeek',
    providerFamily: 'deepseek',
    region: 'domestic',
    status: 'active',
    defaultAvatar: '🧱',
    rolePromptHint: '表达稳、综合能力强，适合均衡型角色。',
    description: 'DeepSeek 通用迭代模型，适合作为综合能力角色。',
  },
  {
    id: 'qwen3-max',
    label: 'Qwen3 Max',
    vendor: '阿里云',
    providerFamily: 'qwen',
    region: 'domestic',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '☁️',
    rolePromptHint: '中文强、知识面广、适合讲清楚复杂问题。',
    description: '通义千问旗舰模型，适合作为中文综合顾问角色。',
  },
  {
    id: 'qwen3-coder-plus',
    label: 'Qwen3 Coder Plus',
    vendor: '阿里云',
    providerFamily: 'qwen',
    region: 'domestic',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '💻',
    rolePromptHint: '工程味重、结构清晰、适合作为技术角色。',
    description: '通义千问代码主力模型，适合作为工程师型角色。',
  },
  {
    id: 'qwen-turbo-2025-07-15',
    label: 'Qwen Turbo',
    vendor: '阿里云',
    providerFamily: 'qwen',
    region: 'domestic',
    status: 'active',
    defaultAvatar: '🫧',
    rolePromptHint: '轻快、便宜、适合高频触达和短回复。',
    description: '通义千问轻量模型，适合作为活跃型角色。',
  },
  {
    id: 'qvq-max',
    label: 'QVQ Max',
    vendor: '阿里云',
    providerFamily: 'qwen',
    region: 'domestic',
    status: 'preview',
    supportsVision: true,
    supportsReasoning: true,
    defaultAvatar: '🖼️',
    rolePromptHint: '偏视觉理解与推理，适合作为视觉型角色。',
    description: '通义千问视觉推理模型，适合作为看图理解角色。',
  },
  {
    id: 'ERNIE-Tiny-8K',
    label: 'ERNIE Tiny 8K',
    vendor: '百度',
    providerFamily: 'ernie',
    region: 'domestic',
    status: 'active',
    defaultAvatar: '🐻',
    rolePromptHint: '轻量、便宜、偏工具型中文互动。',
    description: '百度文心轻量模型，适合作为高并发轻服务角色。',
  },
  {
    id: 'glm-4.5',
    label: 'GLM-4.5',
    vendor: '智谱',
    providerFamily: 'glm',
    region: 'domestic',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '🪐',
    rolePromptHint: '中文推理和综合理解兼顾，适合学院派角色。',
    description: '智谱通用旗舰模型，适合作为理性、学院派角色。',
  },
  {
    id: 'glm-4.5-air',
    label: 'GLM-4.5 Air',
    vendor: '智谱',
    providerFamily: 'glm',
    region: 'domestic',
    status: 'active',
    defaultAvatar: '🌬️',
    rolePromptHint: '更轻、更快，适合作为高频沟通角色。',
    description: '智谱轻量模型，适合作为高频互动角色。',
  },
  {
    id: 'kimi-k2',
    label: 'Kimi K2',
    vendor: '月之暗面',
    providerFamily: 'kimi',
    region: 'domestic',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '🌙',
    rolePromptHint: '长上下文、表达自然，适合作为叙述型角色。',
    description: 'Kimi 长上下文主力模型，适合作为耐聊、能接长线话题角色。',
  },
  {
    id: 'kimi-latest',
    label: 'Kimi Latest',
    vendor: '月之暗面',
    providerFamily: 'kimi',
    region: 'domestic',
    status: 'active',
    defaultAvatar: '🌘',
    rolePromptHint: '口语自然、持续性强，适合作为陪聊角色。',
    description: 'Kimi 通用版本，适合作为连续对话型角色。',
  },
  {
    id: 'hunyuan-t1',
    label: 'Hunyuan T1',
    vendor: '腾讯混元',
    providerFamily: 'hunyuan',
    region: 'domestic',
    status: 'active',
    supportsReasoning: true,
    defaultAvatar: '🔥',
    rolePromptHint: '中文语感稳，适合作为偏现实社交角色。',
    description: '腾讯混元推理模型，适合作为中文社交型角色。',
  },
  {
    id: 'MiniMax-M1',
    label: 'MiniMax M1',
    vendor: 'MiniMax',
    providerFamily: 'minimax',
    region: 'domestic',
    status: 'active',
    supportsAudio: true,
    defaultAvatar: '🎙️',
    rolePromptHint: '适合语音和陪伴场景，表达贴近日常。',
    description: 'MiniMax 主力模型，适合作为语音陪伴和泛娱乐角色。',
  },
  {
    id: 'llama-3.2-1b-instruct',
    label: 'Llama 3.2 1B Instruct',
    vendor: 'Meta',
    providerFamily: 'llama',
    region: 'global',
    status: 'active',
    defaultAvatar: '🦙',
    rolePromptHint: '开源味强、节奏轻，适合作为实验角色。',
    description: 'Meta 开源轻量模型，适合作为边缘设备或实验型角色。',
  },
];

export const INFERENCE_MODEL_CATALOG_SEED = MODEL_SEED_ENTRIES.map(
  (entry, index) => ({
    id: entry.id,
    label: entry.label,
    vendor: entry.vendor,
    providerFamily: entry.providerFamily,
    region: entry.region,
    status: entry.status,
    supportsText: true,
    supportsVision: entry.supportsVision ?? false,
    supportsAudio: entry.supportsAudio ?? false,
    supportsReasoning: entry.supportsReasoning ?? false,
    recommendedRoleName: entry.label,
    defaultAvatar: entry.defaultAvatar,
    rolePromptHint: entry.rolePromptHint,
    description: entry.description,
    sortOrder: index + 1,
  }),
);
